package sentinel

var languageNamesByExtension = map[string]string{
	".c":     "C",
	".cpp":   "C++",
	".cs":    "C#",
	".css":   "CSS",
	".go":    "Go",
	".html":  "HTML",
	".java":  "Java",
	".js":    "JavaScript",
	".json":  "JSON",
	".jsx":   "React",
	".kt":    "Kotlin",
	".md":    "Markdown",
	".php":   "PHP",
	".py":    "Python",
	".rs":    "Rust",
	".sql":   "SQL",
	".swift": "Swift",
	".toml":  "TOML",
	".ts":    "TypeScript",
	".tsx":   "React",
	".txt":   "Text",
	".vue":   "Vue",
	".xml":   "XML",
	".yaml":  "YAML",
	".yml":   "YAML",
}
